name: Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Execute pull on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 165.227.255.220
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_TOKEN }}
          script: |
            cd ~/geocaching
            git pull
